[package]
name = "tinyos"
version = "0.0.0"
authors = ["zgstewart@gmail.com"]

[lib]
path = "kmain.rs"
crate-type = ["staticlib"]

[dependencies]
env-io = { git = "https://github.com/jonathanrlouie/env-io" }
mdo = "0.3.0"
